### ISSUE TITLE
how to get a user's ip on a server using RPC?

### ISSUE THREAD

**Issue by MrEzhUk** [odnoklassniki/one-nio#79]
I want to create minimal auth. I want to check user ip in sever remote function, but I' don't understand how do this...

**Comment by apangin** [comment]
You may subclass `RpcServer` to override `createSession` with your own implementation of `RpcSession`.
In your `RpcSession`, override [`invoke()`](https://github.com/odnoklassniki/one-nio/blob/f9a931e2df60719c629d59826b245aaa85ddd663/src/one/nio/rpc/RpcSession.java#L239) to do whatever auth you want or just store `socket`/`peer` in a ThreadLocal, so that any server method may obtain it.

**Comment by MrEzhUk** [comment]
Thank you!
